In [15]:
import numpy as np
#nutient requirement for 3 crops (n,p,k in kg \ hectare)
#rows :crops (wheat,corn,rice)
#column: nutrients (nitrogen ,phosphorous,pottasium)
nutrient_needs=np.array([
    [120,60,80],#wheat
    [150,75,100],#corn
    [100,50,70]#rice
])
#available fertilizer composition (percentage of n,p,k)
#rows:fertilizer types
#coloumns:nutrient content
fertilizer_composition=np.array([
    [0.20,0.10,0.15],
    [0.15,0.20,0.10],
    [0.10,0.15,0.25]
])
print("Nutrient reqirement (kg\ha):")
print(nutrient_needs)
print("\n Fertilizer compostion:")
print(fertilizer_composition)


#matrix transpose example

print("\n Transpose nutrients need (nutrient X crops:)")
print(nutrient_needs.T)

#calculate fertilizer amounts (solving systen of equation )
#this would normalizing require optimization but for demonstration
total_nutrients_per_crop=np.sum(nutrient_needs,axis=1)
print(f"\n Total nutrient needed per crop :{total_nutrients_per_crop} kg\ha")
#matrix multiplication :calculate total nutrients delivery
#if we apply 100 kg of each fertilizer type
fertilizer_application=np.array([100,100,100])
nutrients_delivered=np.dot(fertilizer_application,fertilizer_composition)
print(f"\n Nutrients from 100 kg each fertilizer :{nutrients_delivered}")
#calculate determinant (for checking if matrix is invertible )
det=np.linalg.det(fertilizer_composition)
print(f"\n Determinant of fertilizer matrix : {det:6f}")
#identity matrix example
scaling =np.eye(3)*1.1 #10% increase
enhanced_needs=np.dot(nutrient_needs,scaling)
print("\n Enchanced nutrient needs (10% increase):")
print(enhanced_needs)

Nutrient reqirement (kg\ha):
[[120  60  80]
 [150  75 100]
 [100  50  70]]

 Fertilizer compostion:
[[0.2  0.1  0.15]
 [0.15 0.2  0.1 ]
 [0.1  0.15 0.25]]

 Transpose nutrients need (nutrient X crops:)
[[120 150 100]
 [ 60  75  50]
 [ 80 100  70]]

 Total nutrient needed per crop :[260 325 220] kg\ha

 Nutrients from 100 kg each fertilizer :[45. 45. 50.]

 Determinant of fertilizer matrix : 0.004625

 Enchanced nutrient needs (10% increase):
[[132.   66.   88. ]
 [165.   82.5 110. ]
 [110.   55.   77. ]]


<>:18: SyntaxWarning: invalid escape sequence '\h'
<>:32: SyntaxWarning: invalid escape sequence '\h'
<>:18: SyntaxWarning: invalid escape sequence '\h'
<>:32: SyntaxWarning: invalid escape sequence '\h'
/tmp/ipython-input-4273907014.py:18: SyntaxWarning: invalid escape sequence '\h'
  print("Nutrient reqirement (kg\ha):")
/tmp/ipython-input-4273907014.py:32: SyntaxWarning: invalid escape sequence '\h'
  print(f"\n Total nutrient needed per crop :{total_nutrients_per_crop} kg\ha")
