In [7]:
import numpy as np
x=np.arange(10)
#x[x%2==0]
print(x[x%2==0])

[0 2 4 6 8]


In [8]:
a=np.array([1,2,3,4,5,6])
print(a[a>3])

[4 5 6]


In [ ]:
#vectorisaion replaces explicit python loops with operations applied to entire arrays at once

In [13]:
a=np.array([10,20,30,40,50])
mask=a>25
idx=np.array([2,3])
print("a[mask]:",a[mask])
print("idx:",a[idx])


a[mask]: [30 40 50]
idx: [30 40]


In [16]:
a=np.array([
    [1,2,3],
    [4,5,6]
])
b=np.array([[1,0,1],[0,1,0]],dtype=bool)
print(a[b])

[1 3 5]


In [24]:
a=np.array([[1,2],[3,4],[5,6]])
x=a[a[:,1]%2==0]
print(a)
print(x)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [28]:
a=np.array([10,20,30,40,50])
idx=np.array([4,0,4,1])
x=a[idx]
print("A:",a)
print("x:",x)

A: [10 20 30 40 50]
x: [50 10 50 20]


In [30]:
a=np.array([
    [1,2],
    [3,4],
    [5,6]
])
mask=np.array([True,False,True])
print(a[mask])

[[1 2]
 [5 6]]


In [31]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([10,20,30])
print(a+b)

[[11 22 33]
 [14 25 36]]


In [36]:
a=np.array([[1,2,3],[4,5,6]])
print((a>2)&(a<6))
x=a[(a>2)&(a<6)]
print(x)

[[False False  True]
 [ True  True False]]
[3 4 5]


In [37]:
a=np.arange(50).reshape(10,5)
selected_rows=a[a[:,0]>20]
x=a[:,0]>20
print(selected_rows)
print(x)

[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[False False False False False  True  True  True  True  True]


In [38]:
a=np.array([1,2,3])
print(2*a)

[2 4 6]


In [39]:
x=np.array([1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9])
mask=(x%2==0)
print(mask)

[False  True False  True False  True False  True False False  True False
  True False  True False  True False]


In [41]:
a=np.array([[1,2],[3,4],[5,4]])
print(a[:,[False,True]])

[[2]
 [4]
 [4]]


In [56]:
a=np.arange(10).reshape(5,2)
print(a)
print(a%5,round(2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1]
 [2 3]
 [4 0]
 [1 2]
 [3 4]] 2
