In [12]:
import numpy as np


#matrix operation are performed on 2d array
#matrix multiplication use .dot(matrix1,matrix2)
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a)
print(b)
matrix_multiplication_result=np.dot(a,b)
element_result=a*b
print("result:","\n",matrix_multiplication_result)
print("element result:","\n",element_result)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
result: 
 [[19 22]
 [43 50]]
element result: 
 [[ 5 12]
 [21 32]]


In [15]:
#transpose= swap rows and colums
#transposed=matrix.T
#transposed=np.transpose(matrix)
a=np.array([[1,2],[3,4]])
transposed=np.transpose(a)
print(a)
print(transposed)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [30]:
#determinant [a]=a  2*2>>> ad-bc
#3*3===== det(A)=a(ei-fg)-b(di-fg)+dh-eg)
#use np.linalg.inv(square_matrix)
#inverse=np.linalg.inv(square_matrix)
#rank=np.linalg.matrix_rank(square_matrix)
a=np.array([[9,5,3],[4,6,3],[9,8,9]])
print(a)
det=np.linalg.det(a)
print("det:",det)
inv=np.linalg.inv(a)
print("inverse:","\n",inv)
rank=np.linalg.matrix_rank(a)
print("rank:",rank)

[[9 5 3]
 [4 6 3]
 [9 8 9]]
det: 159.0
inverse: 
 [[ 0.18867925 -0.13207547 -0.01886792]
 [-0.05660377  0.33962264 -0.09433962]
 [-0.13836478 -0.16981132  0.21383648]]
rank: 3


In [ ]:
1.