In [45]:
import numpy as np
arr=np.array(42)
print(arr)

42


In [46]:
#1D ARRAY
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [47]:
# 2D ARRAY


arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [48]:
#3D ARRAY
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)


print("-------------------------------------------")

arq=np.array([[[1,1],[3,4],[1,2]]])
print(arq)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
-------------------------------------------
[[[1 1]
  [3 4]
  [1 2]]]


In [49]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5,6])
c=np.array([[1,2,3,4],[1,2,3,4]])
d=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])

print(a)
print("-----------------------------------------------")
print(b)
print("-----------------------------------------------")
print(c)
print("-----------------------------------------------")
print(d)
print("-----------------------------------------------")



#use .ndim to find number of dimenion
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

42
-----------------------------------------------
[1 2 3 4 5 6]
-----------------------------------------------
[[1 2 3 4]
 [1 2 3 4]]
-----------------------------------------------
[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
-----------------------------------------------
0
1
2
3


In [50]:
# using ndmin to make high dimension array

import numpy as np
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print('number of dimensions:',arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimensions: 5


In [51]:
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[2]+arr[3])

1
7


In [52]:
import numpy as np
arr=np.array([1,2,3,4,5])
#2D ARRAY(MATRIX)
arr_2d=np.array([[1,2,3],[4,5,6]])
print("-----------------------------------------------")
#using built in function
print("use built in function ")
zeros=np.zeros((3,4))#3*4 array of zeros
ones=np.ones((2,3))# 2*3 array of ones
range_arr=np.arange(0,10,2) #[0,2,4,6,8]
linspace=np.linspace(0,1,5)#5 evenly spaced values fro 0 to 1
identity=np.eye(3)#3*3 identity matrix
random_arr=np.random.rand(3,4) #random values btw 0 and 1
print("zeros:")
print(zeros)
print("-----------------------------------------------")
print("ones")
print(ones)
print("-----------------------------------------------")
print("range arr")
print(range_arr)
print("-----------------------------------------------")
print("lin space ")
print(linspace)
print("-----------------------------------------------")
print("identity")
print(identity)
print("-----------------------------------------------")
print("random arr")
print(random_arr)
print("-----------------------------------------------")



-----------------------------------------------
use built in function 
zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----------------------------------------------
ones
[[1. 1. 1.]
 [1. 1. 1.]]
-----------------------------------------------
range arr
[0 2 4 6 8]
-----------------------------------------------
lin space 
[0.   0.25 0.5  0.75 1.  ]
-----------------------------------------------
identity
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-----------------------------------------------
random arr
[[0.92178133 0.85516503 0.67715409 0.08992321]
 [0.75276842 0.8751322  0.08113695 0.62025427]
 [0.63265353 0.37269526 0.22561274 0.84595733]]
-----------------------------------------------


In [53]:
#a=np.array(list)
x=np.array([1,2,3])
print("x:",x)
a=np.array([[1,2,3,4,5],[4,5,6,7,8]])
print("shape:",a.shape)
print("data:",a.dtype)
print("size:",a.size)
print("nd:",a.ndim)



x: [1 2 3]
shape: (2, 5)
data: int64
size: 10
nd: 2


In [54]:
#(np.sum(array),,,,)( np.mean(array) ,,,,,)(np.max(array),,)( np.min(array) ,,,np.argmax(b) >> b=np.array([10,40,30]) >>>>>index max value
import numpy as np


crop_yield=np.array([
    [12.5,13.2,14.1,13.8,15.2],# farm 1
    [10.3,11.5,10.8,12.1,11.9],#farm 2
    [15.1,14.8,16.2,15.5,16.8],#farm 3
    [11.2,10.9,12.3,11.7,12.8]#farm 4
  ])
print("CROP YIELDS ARRAY (TONS)")
print("-----------------------------------------------")
print(crop_yield)
print("-----------------------------------------------")
print(f"\nShape:{crop_yield.shape}")
print("-----------------------------------------------")
print(f"Data type:{crop_yield.dtype}")
print("-----------------------------------------------")
print(f"Total elements:{crop_yield.size}")
print("-----------------------------------------------")
print(f"Number of dimension:{crop_yield.ndim}")
print("-----------------------------------------------")
print("AGRICULTURAL ANALYSIS OPERATION")
print("-----------------------------------------------")
total_yield=np.sum(crop_yield)
avg_yield_per_farm=np.mean(crop_yield,axis=1)
avg_yield_per_season=np.mean(crop_yield,axis=0)
max_yield=np.max(crop_yield)
min_yield=np.min(crop_yield)
print(f"TOTAL YIELD:{total_yield}TONS")
print(f"AVERAGE PER FARM:{avg_yield_per_farm}TONS")
print(f"AVERAGE PER SEASON:{avg_yield_per_season}TONS")
print(f"MAXIMUN YIELD:{max_yield} tons")
print(f"MINIMUM YIELD:{min_yield}TONS")

best_farm=np.argmax(avg_yield_per_farm)
print(f"\nBEST PERFORMING FARM:{best_farm}")
print(f"Their average yield:{avg_yield_per_farm[best_farm]}")

CROP YIELDS ARRAY (TONS)
-----------------------------------------------
[[12.5 13.2 14.1 13.8 15.2]
 [10.3 11.5 10.8 12.1 11.9]
 [15.1 14.8 16.2 15.5 16.8]
 [11.2 10.9 12.3 11.7 12.8]]
-----------------------------------------------

Shape:(4, 5)
-----------------------------------------------
Data type:float64
-----------------------------------------------
Total elements:20
-----------------------------------------------
Number of dimension:2
-----------------------------------------------
AGRICULTURAL ANALYSIS OPERATION
-----------------------------------------------
TOTAL YIELD:262.7TONS
AVERAGE PER FARM:[13.76 11.32 15.68 11.78]TONS
AVERAGE PER SEASON:[12.275 12.6   13.35  13.275 14.175]TONS
MAXIMUN YIELD:16.8 tons
MINIMUM YIELD:10.3TONS

BEST PERFORMING FARM:2
Their average yield:15.679999999999998
